language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'

env:
  - DB=mysql
  - DB=pgsql


before_install:
  - sh -c "if [ "$DB" == "pgsql" ]; then psql -c 'DROP DATABASE IF EXISTS phprs;" -U postgres;' fi"  
  - sh -c "if [ "$DB" == "pgsql" ]; then psql -c 'create database phprs;" -U postgres;' fi"
  - sh -c "if [ "$DB" == "mysql" ]; then mysql -e 'create database IF NOT EXISTS phprs;' -uroot; fi"

before_script:
  - composer self-update
  - composer install

script: 
  - phpunit src/Novosga/Test/TestConectionDB_$DB.php